"""Export research entries as a Markdown or PDF report."""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"
ACCENT = "#4b3bd6"
BODY_PT = 10.5


KIND_LABEL = {"web": "Web research", "papers": "Literature review", "documents": "Document Q&A"}


def _source_line(s: dict) -> str:
    title = s.get("title") or s.get("url") or "Source"
    bits = []
    if s.get("authors"):
        authors = s["authors"]
        bits.append(", ".join(authors[:3]) + (" et al." if len(authors) > 3 else ""))
    if s.get("year"):
        bits.append(str(s["year"]))
    if s.get("page"):
        bits.append(f"page {s['page']}")
    if s.get("domain") and not s.get("page"):
        bits.append(s["domain"])
    head = f"[{title}]({s['url']})" if s.get("url") else f"**{title}**"
    return f"{head}" + (f" — {'; '.join(bits)}" if bits else "")


def to_markdown(entries: list[dict], title: str | None = None) -> str:
    title = title or (entries[0]["question"] if len(entries) == 1 else "Research Report")
    out = [f"# {title}", "", f"*Generated by Probelyn on {datetime.now():%d %B %Y}*", ""]
    if len(entries) > 1:
        out += ["## Contents", ""]
        out += [f"{i}. {e['question']}" for i, e in enumerate(entries, start=1)]
        out.append("")
    for i, e in enumerate(entries, start=1):
        heading = e["question"] if len(entries) == 1 else f"{i}. {e['question']}"
        out += [
            f"## {heading}",
            "",
            f"*{KIND_LABEL.get(e['kind'], e['kind'])} · {e['created_at'][:10]}"
            + (f" · model: {e['model']}" if e.get("model") else "")
            + "*",
            "",
            e["answer"].strip(),
            "",
        ]
        if e["sources"]:
            out += ["### Sources", ""]
            out += [f"{s.get('n', j)}. {_source_line(s)}" for j, s in enumerate(e["sources"], start=1)]
            out.append("")
    return "\n".join(out).strip() + "\n"


# ---------------------------------------------------------------------- PDF
# A small purpose-built Markdown renderer on top of fpdf2's multi_cell(markdown=True).
# It handles what the model and to_markdown() emit: headings, paragraphs, bullet and
# numbered lists, block quotes, fenced code, links and **bold** / *italic* text.

_LINK = re.compile(r"\[([^\]]+)\]\((https?://[^)\s]+)\)")
_ITALIC = re.compile(r"(?<![*\w])[*_](?![*\s])(.+?)(?<![*\s])[*_](?![*\w])")


class _ReportPDF(FPDF):
    base_font = "helvetica"
    mono_font = "courier"

    def footer(self):
        self.set_y(-12)
        self.set_font(self.base_font, size=8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 8, f"Probelyn report  ·  page {self.page_no()}", align="C")


def _setup_fonts(pdf: _ReportPDF) -> bool:
    regular = FONT_DIR / "DejaVuSans.ttf"
    if not regular.exists():
        return False
    pdf.add_font("DejaVu", "", str(regular))
    for style, name in (("B", "Bold"), ("I", "Oblique"), ("BI", "BoldOblique")):
        f = FONT_DIR / f"DejaVuSans-{name}.ttf"
        pdf.add_font("DejaVu", style, str(f if f.exists() else regular))
    pdf.base_font = "DejaVu"
    mono = FONT_DIR / "DejaVuSansMono.ttf"
    if mono.exists():
        pdf.add_font("DejaVuMono", "", str(mono))
        pdf.mono_font = "DejaVuMono"
    return True


def _inline(text: str) -> str:
    """Convert Markdown inline syntax to fpdf2's markdown flavour."""
    text = text.replace("--", "\u2013").replace("__", "_")
    text = _LINK.sub(lambda m: f"{m.group(1)} ({m.group(2)})", text)
    text = _ITALIC.sub(r"__\1__", text)
    return text.replace("`", "")


class _Renderer:
    def __init__(self, pdf: _ReportPDF):
        self.pdf = pdf

    def text(self, txt: str, size=BODY_PT, style="", color=(33, 37, 48), indent=0.0, lh=1.5, mono=False):
        pdf = self.pdf
        pdf.set_font(pdf.mono_font if mono else pdf.base_font, style, size)
        pdf.set_text_color(*color)
        pdf.set_x(pdf.l_margin + indent)
        pdf.multi_cell(0, size * 0.3528 * lh, txt, markdown=not mono, align="L", new_x="LMARGIN", new_y="NEXT")

    def space(self, mm: float):
        self.pdf.ln(mm)

    def heading(self, level: int, txt: str):
        size = {1: 19, 2: 14.5, 3: 12}.get(level, BODY_PT + 0.5)
        self.space({1: 2, 2: 5, 3: 3}.get(level, 2))
        self.text(_inline(txt).replace("**", ""), size=size, style="B", color=_rgb(ACCENT), lh=1.3)
        if level <= 2:
            y = self.pdf.get_y() + 0.8
            self.pdf.set_draw_color(225, 225, 235)
            self.pdf.line(self.pdf.l_margin, y, self.pdf.w - self.pdf.r_margin, y)
            self.space(2.5)
        else:
            self.space(1)

    def list_item(self, marker: str, txt: str, depth: int):
        pdf = self.pdf
        indent = 3 + depth * 6
        pdf.set_font(pdf.base_font, "B", BODY_PT)
        pdf.set_text_color(*_rgb(ACCENT))
        y = pdf.get_y()
        pdf.set_xy(pdf.l_margin + indent, y)
        pdf.cell(6, BODY_PT * 0.3528 * 1.5, marker)
        pdf.set_xy(pdf.l_margin + indent + 6, y)
        pdf.set_font(pdf.base_font, "", BODY_PT)
        pdf.set_text_color(33, 37, 48)
        pdf.multi_cell(
            0, BODY_PT * 0.3528 * 1.5, _inline(txt), markdown=True, align="L", new_x="LMARGIN", new_y="NEXT"
        )
        self.space(0.8)

    def render(self, markdown_text: str):
        lines = markdown_text.splitlines()
        i, para = 0, []

        def flush():
            if para:
                self.text(_inline(" ".join(para)))
                self.space(2)
                para.clear()

        while i < len(lines):
            raw = lines[i]
            line = raw.strip()
            if line.startswith("```"):
                flush()
                code = []
                i += 1
                while i < len(lines) and not lines[i].strip().startswith("```"):
                    code.append(lines[i])
                    i += 1
                self.text("\n".join(code), size=8.5, color=(60, 60, 70), indent=3, lh=1.35, mono=True)
                self.space(2)
            elif not line:
                flush()
            elif m := re.match(r"^(#{1,6})\s+(.*)", line):
                flush()
                self.heading(len(m.group(1)), m.group(2))
            elif re.match(r"^(-{3,}|\*{3,})$", line):
                flush()
                self.space(3)
            elif m := re.match(r"^(\s*)([-*+]|\d+[.)])\s+(.*)", raw):
                flush()
                depth = len(m.group(1).replace("\t", "    ")) // 2
                marker = "\u2022" if m.group(2) in "-*+" else m.group(2).rstrip(")").rstrip(".") + "."
                if self.pdf.base_font == "helvetica" and marker == "\u2022":
                    marker = "-"
                self.list_item(marker, m.group(3), min(depth, 3))
            elif line.startswith(">"):
                flush()
                self.text(_inline(line.lstrip("> ")), color=(95, 99, 112), indent=5, style="")
                self.space(1.5)
            elif line.startswith("|"):
                flush()
                if not re.match(r"^\|[\s:|-]+\|$", line):  # skip separator rows
                    cells = [c.strip() for c in line.strip("|").split("|")]
                    self.text(_inline("  |  ".join(cells)), size=9.5)
            else:
                para.append(line)
            i += 1
        flush()


def _rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


def to_pdf(entries: list[dict], title: str | None = None) -> bytes:
    text = to_markdown(entries, title)
    pdf = _ReportPDF(format="A4")
    if not _setup_fonts(pdf):  # core fonts are latin-1 only
        text = text.encode("latin-1", "replace").decode("latin-1")
    pdf.set_margins(20, 18, 20)
    pdf.set_auto_page_break(True, margin=20)
    pdf.set_title(title or "Probelyn report")
    pdf.set_author("Probelyn")
    pdf.add_page()
    _Renderer(pdf).render(text)
    return bytes(pdf.output())


def safe_filename(name: str) -> str:
    name = re.sub(r"[^\w\s-]", "", name).strip().replace(" ", "-")
    return (name[:60] or "report").lower()
